apiVersion: 1

datasources:
  - name: Supabase Analytics
    type: postgres
    url: db:5432
    database: _supabase
    user: supabase_admin
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      database: _supabase
      schema: _analytics
